#!/usr/bin/env bash
# Creates a MYSQL dump of all databases and creates a dated compressed archive from it
mysqldump -u root -p"$1" --all-databases > backup.sql

if [ -f backup.sql ]
then
        tar cfz "$(date '+%Y-%m-%d').tar.gz" backup.sql
fi
