#!/usr/bin/env bash
# Configures an Ubuntu server with the following requirements:
#        - localhost resolves to 127.0.0.2
#        - facebook.com resolves to 8.8.8.8

cp /etc/hosts ~/hosts.new
echo -e "127.0.0.2\tlocalhost\n8.8.8.8\tfacebook.com" > ~/hosts.new
cat ~/hosts.new > /etc/hosts
